version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: laravel-app:8.4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: any
    volumes:
      - ./.env:/var/www/.env
      - public_data:/var/www/public
      - storage_data:/var/www/storage
      - cache_data:/var/www/bootstrap/cache
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      REDIS_HOST: valkey
    networks:
      laravel-net:
        aliases:
          - db
          - valkey

  db:
    image: mysql:9.4.0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: any
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      laravel-net:
        aliases:
          - db

  valkey:
    image: valkey/valkey:8.1-alpine
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: any
    volumes:
      - valkey_data:/data
    networks:
      laravel-net:
        aliases:
          - valkey

  nginx:
    image: nginx:1.29.1-alpine
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: any
    volumes:
      - public_data:/var/www/public:ro
      - storage_data:/var/www/storage:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites/laravel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      laravel-net:
        aliases:
          - nginx

networks:
  laravel-net:
    driver: overlay

volumes:
  storage_data:
    driver: local
  cache_data:
    driver: local
  db_data:
    driver: local
  valkey_data:
    driver: local
  public_data:
    driver: local